load("@rules_intellij_generate//:def.bzl", "intellij_project_group")
intellij_project_group(
  name="all_scenario_projects",
  intellij_projects=[
    "//01_one_class:01proj",
    "//02_one_class_and_one_test:02proj",
    "//03_basic:03proj",
    "//04_transitive_via_export:04proj",
    "//05_annotation_processor:05proj",
    "//scenario_tests:scenariotestsproj",
  ],
)