package(default_visibility = ["//:__subpackages__"])

exports_files(["iml_types.xml"])

filegroup(
    name = "automatically_placed_intellij_project_files",
    srcs = glob(["intellij_project_files/**/*.xml"]),
)
