load("@rules_intellij_generate//:def.bzl", "intellij_project_group")
intellij_project_group(
  name="all_scenario_projects",
  intellij_projects=[
    "//01_one_class:idea_project",
    "//02_one_class_and_one_test:idea_project",
    "//03_basic:idea_project",
    "//04_transitive_via_export:idea_project",
    "//05_annotation_processor:idea_project",
    "//06_protobuf_messages:idea_project",
    "//07_grpc:idea_project",
    "//08_auto_value:idea_project",
    "//scenario_tests:idea_project",
  ],
)