workspace(name="rules_intellij_generate_scenarios")

maven_jar(name="com_google_guava_guava",         artifact="com.google.guava:guava:19.0")

local_repository(
    name = "rules_intellij_generate",
    path = "../rules",
)

load("@rules_intellij_generate//:def.bzl", "repositories_for_intellij_generate")
repositories_for_intellij_generate()

local_repository(
    name = "rules_junit5",
    path = "../rules_junit5",
)
load("@rules_junit5//:def.bzl", "junit5_repositories")
junit5_repositories()
