# Loads the extension bazel project, using a relative path.
#
# All public-scoped targets in that project are available for use
# in this bazel project.
#
# Per bazel target syntax:
#
# Root of extension:
# @rules_intellij_generate//
#
# A target with the name foo,
# marked visibility = ["//visibility:public"], is addressed as:
# @rules_intellij_generate//:foo
local_repository(
    name = "rules_intellij_generate",
    path = "../../extension",
)

