package(default_visibility = ["//:__subpackages__"])

java_proto_library(
    name = "plain_email_java_proto",
    deps = [":plain_email_proto"],
)

proto_library(
    name = "plain_email_proto",
    srcs = ["src/main/proto/plain_email.proto"],
)